In [1]:
!pip install seaborn

Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /opt/saturncloud/envs/saturn/lib/python3.11/site-packages (from seaborn) (1.26.4)
Requirement already satisfied: pandas>=1.2 in /opt/saturncloud/envs/saturn/lib/python3.11/site-packages (from seaborn) (2.3.1)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /opt/saturncloud/envs/saturn/lib/python3.11/site-packages (from seaborn) (3.10.1)
Requirement already satisfied: contourpy>=1.0.1 in /opt/saturncloud/envs/saturn/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /opt/saturncloud/envs/saturn/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/saturncloud/envs/saturn/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.60.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/saturncloud/envs/saturn/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /opt/saturncloud/envs/saturn/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (25.0)
Requirement already satisfied: pillow>=8 in /opt/saturncloud/envs/saturn/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/saturncloud/envs/saturn/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in /opt/saturncloud/envs/saturn/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/saturncloud/envs/saturn/lib/python3.11/site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/saturncloud/envs/saturn/lib/python3.11/site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/saturncloud/envs/saturn/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Installing collected packages: seaborn
Successfully installed seaborn-0.13.2

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('distance_df_kai.csv')

In [4]:
df

,Unnamed: 0,atom1_name,atom1_residue,atom1_residue_num,atom1_insertion_code,atom1_chain_id,atom2_name,atom2_residue,atom2_residue_num,atom2_insertion_code,atom2_chain_id,distance,dock
0,0,CE2,TYR,370,,A,N,TYR,1,,DRUG,22.380392,reta_GIP_7BRT
1,1,CD2,TYR,370,,A,N,TYR,1,,DRUG,22.668829,reta_GIP_7BRT
2,2,CD2,LEU,372,,A,N,TYR,1,,DRUG,22.775736,reta_GIP_7BRT
3,3,CE2,TYR,370,,A,CA,TYR,1,,DRUG,23.025286,reta_GIP_7BRT
4,4,OH,TYR,370,,A,N,TYR,1,,DRUG,23.192477,reta_GIP_7BRT
...,...,...,...,...,...,...,...,...,...,...,...,...,...
35395641,35395641,CD,GLU,460,,F,O,GLY,29,,DRUG,118.177283,tirz_GIP_7BRT
35395642,35395642,OE2,GLU,460,,F,O,ALA,28,,DRUG,118.204987,tirz_GIP_7BRT
35395643,35395643,OE1,GLU,460,,F,O,GLY,29,,DRUG,118.244896,tirz_GIP_7BRT
35395644,35395644,OE2,GLU,460,,F,CA,GLY,29,,DRUG,118.579948,tirz_GIP_7BRT
35395645,35395645,OE2,GLU,460,,F,O,GLY,29,,DRUG,118.893737,tirz_GIP_7BRT

In [4]:
min(df.distance)

0.7478604395636672

In [6]:
df_filt = df[df['distance'] < 4]

In [7]:
df_filt

,Unnamed: 0,atom1_name,atom1_residue,atom1_residue_num,atom1_insertion_code,atom1_chain_id,atom2_name,atom2_residue,atom2_residue_num,atom2_insertion_code,atom2_chain_id,distance,dock
2713132,2713132,OE1,GLN,221,,F,OH,TYR,1,,DRUG,1.615041,reta_GIP_7BRT
2713133,2713133,NE2,GLN,44,,F,O,GLY,34,,DRUG,2.093586,reta_GIP_7BRT
2713134,2713134,OE2,GLU,359,,F,OG1,THR,5,,DRUG,2.173192,reta_GIP_7BRT
2713135,2713135,CD,GLN,221,,F,OH,TYR,1,,DRUG,2.547633,reta_GIP_7BRT
2713136,2713136,O,GLN,27,,F,OD2,ASP,15,,DRUG,2.587232,reta_GIP_7BRT
...,...,...,...,...,...,...,...,...,...,...,...,...,...
34329943,34329943,CE1,TYR,84,,F,CD1,LEU,26,,DRUG,3.992345,tirz_GIP_7BRT
34329944,34329944,CA,THR,28,,F,CG,ASP,15,,DRUG,3.992604,tirz_GIP_7BRT
34329945,34329945,CB,ASN,287,,F,OG,SER,8,,DRUG,3.992948,tirz_GIP_7BRT
34329946,34329946,CG,ASN,117,,F,NZ,LYS,20,,DRUG,3.994364,tirz_GIP_7BRT
34329947,34329947,NE1,TRP,36,,F,CG,LEU,26,,DRUG,3.997080,tirz_GIP_7BRT

In [8]:
dock_dict = (
    df_filt.groupby('dock')['atom2_residue_num']
    .apply(lambda x: sorted(x.unique()))
    .to_dict()
)

print(dock_dict)

{'glp1_GIP_7BRT': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 17, 18, 19, 20, 21, 22, 23, 25, 26, 27, 31], 'glp1_GLP_6XOX': [1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 25, 26, 27, 30, 31], 'kai_GIP_7BRT': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 29, 30, 31, 32, 33, 34, 35], 'kai_GLP_6XOX': [1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 18, 19, 20, 21, 22, 23, 25, 26, 27, 29, 30, 31, 32, 33, 34, 35, 36, 37], 'reta_GIP_7BRT': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 22, 23, 25, 26, 27, 30, 31, 32, 34], 'reta_GLP_6XOX': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 32, 33, 35, 36, 37, 38], 'sema_GIP_7BRT': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 17, 18, 19, 20, 21, 22, 23, 25, 26, 27, 30], 'sema_GLP_6XOX': [1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 25, 26, 27, 29, 30], 'tirz_GIP_7BRT': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 15, 16, 17, 18, 19, 20, 22, 23, 26, 27, 30], 'tirz_GLP_6XOX': [1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 25, 26, 27, 28, 31, 32, 33, 34, 35, 36, 38]}